### PR TITLE
Mlb roster

### PR DESCRIPTION
**Pull request by RinkeRiezebos**
I Alex,

I added the mlb_roster method. Could you please test it (if you want - it works for me) and pull it? Please see my notes and the issue I filed: https://erikberg.com/api/issues/197. Let me know how you want to deal with it.

Cheers!
Rinke

### CODE REVIEW

**Comment by alexmchale** [comment]
I'm sorry this took me so long to get to. Thank you for submitting this. I've merged these changes.

**Comment by RinkeRiezebos** [comment]
awesome, no problem. Thanks for merging.

**Comment by alexmchale** [comment]
Version `1.7.0` includes this feature. Thank you!

**Comment by RinkeRiezebos** [comment]
:)

**Pull request merged**
